name = "EquationalTest"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["EquationalTest"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`
autoImplicit = false

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.20.0-rc2"

[[require]]
name = "Duper"
scope = "leanprover-community"
rev = "v4.20.0-rc2"

[[lean_lib]]
name = "EquationalTest"
